using System;

namespace Alphabet_Triangle
{
    class Program
    {
        static void Main(string[] args)
        {
            char ch='A';      
       int i, j, k, m;      
       for(i=1; i<=6; i++)      
       {      
        for(j=5; j>=i; j--)      
         Console.Write(" ");      
        for(k=1;k<=i;k++)      
         Console.Write(ch++);      
        ch--;      
        for(m=1;m<i;m++)      
         Console.Write(--ch);      
        Console.Write("\n");      
        ch='A';      
       }      
   }  
  }  
}
/* 
C# Program to Print Alphabet Triangle

There are different triangles that can be printed.
Triangles can be generated by alphabets or numbers.
In this C# program, we are going to print alphabet triangles. */